<?php

return [
    'adminEmail' => 'admin@example.com',
    'contentModules' => [
        /**
         * app-models-Article' => [
         *    id' => 'articles', // 控制器名称（唯一）
         *    label' => 'Articles', //  需要翻译的文本（app.php）
         *    url' => ['/articles/index'], // 访问 URL
         *    embedSiteManangement' => true, // 是否显示在站点管理项目中，如果想独立出来，可以设置为 false, 默认为 true
         * ],
         */
        'app-models-Ad' => [
            'id' => 'ads',
            'label' => 'Ads',
            'url' => ['/ads/index'],
            'embedSiteManangement' => false,
        ],
        'app-models-AdSpace' => [
            'id' => 'ad-spaces',
            'label' => 'Ad Spaces',
            'url' => ['/ad-spaces/index'],
            'embedSiteManangement' => false,
        ],
        'app-models-Label' => [
            'id' => 'labels',
            'label' => 'Labels',
            'url' => ['/labels/index'],
            'embedSiteManangement' => false,
        ],
        'app-models-Album' => [
            'id' => 'albums',
            'label' => 'Albums',
            'url' => ['/albums/index'],
            'enabled' => false,
            'activeItems' => ['albums', 'album-photos'],
            'needAudit' => true,
        ],
        'app-models-Article' => [
            'id' => 'articles',
            'label' => 'Articles',
            'url' => ['/articles/index'],
            'enabled' => true,
        ],
        'app-models-ClassicCase' => [
            'id' => 'cases',
            'label' => 'Cases',
            'url' => ['/cases/index'],
            'enabled' => true,
            'needAudit' => true,
        ],
        'app-models-Download' => [
            'id' => 'downloads',
            'label' => 'Downloads',
            'url' => ['/downloads/index'],
            'enabled' => true,
            'needAudit' => true,
        ],
        'app-models-Faq' => [
            'id' => 'faqs',
            'label' => 'Faqs',
            'url' => ['/faqs/index'],
            'enabled' => true,
            'needAudit' => true,
        ],
        'app-models-Feedback' => [
            'id' => 'feedbacks',
            'label' => 'Feedbacks',
            'url' => ['/feedbacks/index'],
            'enabled' => false,
        ],
        'app-models-FileUploadConfig' => [
            'id' => 'file-upload-configs',
            'label' => 'File Upload Configs',
            'url' => ['/file-upload-configs/index'],
            'embedSiteManangement' => false,
        ],
        'app-models-FriendlyLink' => [
            'id' => 'friendly-links',
            'label' => 'Friendly Links',
            'url' => ['/friendly-links/index'],
            'enabled' => true,
        ],
        'app-models-GroupOption' => [
            'id' => 'group-options',
            'label' => 'Group Options',
            'url' => ['/group-options/index'],
            'embedSiteManangement' => false,
        ],
        'app-models-IpAccessRule' => [
            'id' => 'ip-access-rules',
            'label' => 'IP Access Rules',
            'url' => ['/ip-access-rules/index'],
            'embedSiteManangement' => false,
        ],
        'app-models-Lookup' => [
            'id' => 'lookups',
            'label' => 'Lookups',
            'url' => ['/lookups/index'],
            'embedSiteManangement' => false,
        ],
        'app-models-Meta' => [
            'id' => 'meta',
            'label' => 'Meta',
            'url' => ['/meta/index'],
            'embedSiteManangement' => false,
        ],
        'app-models-News' => [
            'id' => 'news',
            'label' => 'News',
            'url' => ['/news/index'],
            'enabled' => true,
            'needAudit' => true,
        ],
        'app-models-Node' => [
            'id' => 'nodes',
            'label' => 'Nodes',
            'url' => ['/nodes/index'],
            'embedSiteManangement' => false,
        ],
        'app-models-Product' => [
            'id' => 'products',
            'label' => 'Products',
            'url' => ['/products/index'],
            'enabled' => false,
            'needAudit' => true,
        ],
        'app-models-QuickUrlShortcut' => [
            'id' => 'quick-url-shortcuts',
            'label' => 'Quick Url Shortcuts',
            'url' => ['/quick-url-shortcuts/index'],
        ],
        'app-models-SearchKeyword' => [
            'id' => 'search-keywords',
            'label' => 'Search Keywords',
            'url' => ['/search-keywords/index'],
            'enabled' => true,
            'needAudit' => false,
        ],
        'app-models-Slide' => [
            'id' => 'slides',
            'label' => 'Slides',
            'url' => ['/slides/index'],
            'enabled' => false,
        ],
        'app-models-BootDatum' => [
            'id' => 'boot-data',
            'label' => 'Boot Data',
            'url' => ['/boot-data/index'],
            'enabled' => true,
        ],
        'app-models-Tag' => [
            'id' => 'tags',
            'label' => 'Tags',
            'url' => ['/tags/index'],
            'embedSiteManangement' => false,
        ],
        'app-models-Video' => [
            'id' => 'videos',
            'label' => 'Videos',
            'url' => ['/videos/index'],
            'enabled' => false,
            'needAudit' => true,
        ],
        'app-models-Vote' => [
            'id' => 'votes',
            'label' => 'Votes',
            'url' => ['/votes/index'],
            'enabled' => false,
            'needAudit' => true,
        ],
        'app-models-WorkflowRule' => [
            'id' => 'workflow-rules',
            'label' => 'Workflow Rules',
            'url' => ['/workflow-rules/index'],
            'embedSiteManangement' => false,
        ],
    ],
    'gridColumns' => [
        'app-models-Ad' => [
            'space_id',
            'name',
            'url',
            'type',
            'begin_datetime',
            'end_datetime',
            'message',
            'views_count',
            'hits_count',
            'status',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-AdSpace' => [
            'group_id',
            'alias',
            'name',
            'width',
            'height',
            'description',
            'ads_count',
            'status',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-Archive' => [
            'node_id',
            'model_name',
            'title',
            'keywords',
            'description',
            'tags',
            'has_thumbnail',
            'author',
            'source',
            'status',
            'enabled',
            'published_datetime',
            'clicks_count',
            'enabled_comment',
            'comments_count',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-Album' => [
            'ordering',
            'node_id',
            'group_id',
            'title',
            'short_title',
            'keywords',
            'tags',
            'photos_count',
            'hits_count',
            'status',
            'enabled',
            'task.status',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-Article' => [
            'ordering',
            'alias',
            'title',
            'tags',
            'keywords',
            'status',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-BasicCode' => [
            'ordering',
            'type',
            'code',
            'value',
            'description',
            'parent_ids',
            'parent_names',
            'status',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-ClassicCase' => [
            'node_id',
            'alias',
            'title',
            'keywords',
            'tags',
            'hits_count',
            'status',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-Download' => [
            'ordering',
            'node_id',
            'group_id',
            'title',
            'tags',
            'keywords',
            'software_support_os',
            'software_copyright_type',
            'software_language',
            'software_version',
            'star_rating',
            'hits_count',
            'downloads_count',
            'status',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-Faq' => [
            'ordering',
            'node_id',
            'title',
            'tags',
            'keywords',
            'hits_count',
            'status',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-Feedback' => [
            'group_id',
            'username',
            'tel',
            'email',
            'title',
            'ip_address',
            'status',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
        ],
        'app-models-FriendlyLink' => [
            'ordering',
            'group_id',
            'type',
            'title',
            'description',
            'url',
            'url_open_target',
            'status',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-Lookup' => [
            'label',
            'description',
            'value',
            'return_type',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-Meta' => [
            'model_name',
            'name',
            'form_field_type',
            'db_field_type',
            'validator_rule',
            'validator_required',
            'description',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-News' => [
            'ordering',
            'node_id',
            'title',
            'short_title',
            'keywords',
            'tags',
            'author',
            'source',
            'status',
            'enabled',
            'enabled_comment',
            'comments_count',
            'hits_count',
            'up_count',
            'down_count',
            'published_at',
            'task.status',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-Product' => [
            'ordering',
            'node_id',
            'sn',
            'name',
            'alias',
            'keywords',
            'tags',
            'price',
            'pictures_count',
            'hits_count',
            'status',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ],
        'app-models-Video' => [
            'ordering',
            'group_id',
            'node_id',
            'title',
            'short_title',
            'tags',
            'keywords',
            'path_type',
            'hits_count',
            'play_times',
            'status',
            'enabled',
            'created_by',
            'created_at',
            'updated_by',
            'updated_at',
            'deleted_by',
            'deleted_at'
        ]
    ],
];
